# Generated by Django 5.1.7 on 2025-04-27 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_prevencion', '0012_indicador_fecha_aprobacion_indicador_fecha_rechazo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicador',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='medida',
            name='comunas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyecto_prevencion.comunaplan'),
        ),
        migrations.AddField(
            model_name='medida',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
