name: Proyecto CI

on:
  pull_request:
    branches: [main]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest coverage

      - name: Run tests with coverage
        working-directory: ./plan_prevencion
        run: |
          coverage run --source=. -m pytest ../proyecto_prevencion/tests

      - name: Check coverage percentage (fail if < 70%)
        working-directory: ./plan_prevencion
        run: |
          coverage report --fail-under=70
          coverage xml

      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: plan_prevencion/coverage.xml
